from dmcr.datamodels.pipeline.Datamodels import DatamodelPipeline
from dmcr.datamodels.pipeline.DatamodelsIndexBasedNQPipeline import DatamodelsIndexBasedNQPipeline
from dmcr.datamodels.pipeline.DatamodelsNQPipeline import DatamodelsNQPipeline
